# Generated by Django 6.1 on 2026-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'DRAFT'), ('Published', 'PUBLISHED')], default='Draft', max_length=20),
        ),
    ]
